spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/hire-sense}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        enable_lazy_load_no_trans: true
        jdbc:
          time_zone: UTC
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: update
server:
  port: 8080
  servlet:
    context-path: /api/v1